### ISSUE TITLE
Fix the flaky test padl.creator.classfile.test.visitor.Composite1

### ISSUE THREAD

**Issue by yann-gael** [ptidejteam/ptidej-Ptidej#7]
The test `padl.creator.classfile.test.visitor.Composite1` is flaky: sometimes is passes, sometimes it fails without clear reasons.  Fix/Change it so that it is consistent.

**Comment by LVoisard** [comment]
I wasn't able to fix this issue or find what causes it yet but here is what I found out:

- I was able to reproduce the problem magically by editing the expected.txt in resources and reversing my changes, making it the same as it used to be, but now the tests failed.
- I then fixed the issue by doing a clean install of the entire project (not just PADL Analysis).

Next time the issue happens, I suggest looking at PADL Creator Classfiles, since the generator uses this module for the visitor test.


We also investigated whether the problem was an issue of CR LF however it was not the case

**Comment by yann-gael** [comment]
See https://github.com/ptidejteam/ptidej-Ptidej/commit/61390a88fb8a4ea65cb4024d09df9d209428f838 for two new files showing two different outputs with "swapped" `IMethodInvocation`s, hence the flakiness...

**Comment by yann-gael** [comment]
Fixed in [24d63da](https://github.com/ptidejteam/ptidej-Ptidej/commit/24d63daf6e2fb6c20805b3c1c368cbba5425bfa7)
